In [17]:
from data_helpers import fit_pca

feature = fit_pca()
train_datasets, validation_datasets, test_datasets, expected_RUL_datasets = feature.result_df()
train_datasets[0]

,Unit Number,Time (Cycles),PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10
0,2,1,-4.888067,-0.073280,-0.191105,0.136955,6.556338,0.060633,0.037273,-0.488832,-0.484605,-0.179209
1,2,2,-4.333902,-0.150475,-0.665323,1.892024,-1.031432,0.547361,0.711206,-0.076884,0.060578,0.293545
2,2,3,-5.003945,0.224774,-0.568979,1.958785,5.966880,0.902570,0.560002,-0.524460,0.305597,0.092361
3,2,4,-5.107367,0.365191,-0.194350,1.811717,-1.145077,0.410198,0.385573,-0.290448,-0.288587,0.655261
4,2,5,-5.464810,0.203329,-0.452717,1.338957,6.111575,-0.381631,-0.331347,-0.626438,0.573540,0.518663
...,...,...,...,...,...,...,...,...,...,...,...,...
16109,100,196,6.962576,-0.877323,0.938418,0.648615,0.005334,-0.627832,0.592017,0.009544,0.895433,-0.693938
16110,100,197,7.102584,-0.945318,1.842089,0.656173,-0.090673,0.644176,-0.373444,-0.653792,-1.055729,-0.208923
16111,100,198,8.083038,-0.690145,-0.041760,0.281251,0.320375,-0.329894,1.140073,-0.269687,0.766491,0.350538
16112,100,199,7.826214,-0.745422,-0.291177,-0.851751,0.738067,0.668139,-0.142457,-1.429173,-0.333743,0.091077
16113,100,200,7.925748,-1.268775,2.339487,0.179086,0.075909,-0.316345,-0.330164,-0.071645,-0.073398,-0.531459

In [18]:
validation_datasets[0]

,Unit Number,Time (Cycles),PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10
0,1,1,-2.708793,-0.482522,1.180459,0.510939,-0.656545,0.735046,0.670431,-0.341657,0.057422,0.653805
1,1,2,-2.124134,-0.827167,0.130960,1.165523,-0.696662,0.936648,0.329073,-0.052997,-0.311403,0.653111
2,1,3,-2.734900,-0.607813,0.563753,-2.122523,0.358568,0.574824,-1.078405,-0.507760,0.298345,0.116528
3,1,4,-3.134584,-0.889775,-0.262956,0.120436,-0.340217,-0.369613,-0.056628,0.112321,-0.121045,-1.108165
4,1,5,-2.192166,-0.417691,1.026407,-0.295209,-0.344853,-0.741647,0.314177,0.084420,-0.505092,0.198059
...,...,...,...,...,...,...,...,...,...,...,...,...
4512,92,337,6.272256,3.336349,-0.849942,0.907094,-0.097239,-0.041461,-0.011238,0.009163,-0.298221,0.087997
4513,92,338,7.278000,3.512381,-0.373529,-1.433674,0.729698,-0.500436,-0.981628,0.270365,0.088548,-0.839520
4514,92,339,7.393815,3.582849,0.075628,-1.422593,0.682454,0.479021,-0.539297,-1.026955,0.553315,-0.320164
4515,92,340,7.633117,3.386969,-1.741670,-0.459706,0.583653,-0.676116,-0.747281,0.297996,0.499912,0.542817
4516,92,341,8.159130,3.981281,1.009718,0.890971,-0.212145,0.194334,-0.257153,0.102999,-0.780488,-0.199368

In [19]:
def Calculate_RUL(df):
    max_cycles = df.groupby('Unit Number')['Time (Cycles)'].max()
    merged = df.merge(max_cycles.to_frame(name='max_time_cycle'), left_on='Unit Number',right_index=True)
    merged["RUL"] = merged["max_time_cycle"] - merged['Time (Cycles)']
    merged = merged.drop("max_time_cycle", axis=1)
    return merged

In [20]:
for i in range(4):
    train_datasets[i] = Calculate_RUL(train_datasets[i])

In [21]:
train_datasets[0]

,Unit Number,Time (Cycles),PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10,RUL
0,2,1,-4.888067,-0.073280,-0.191105,0.136955,6.556338,0.060633,0.037273,-0.488832,-0.484605,-0.179209,286
1,2,2,-4.333902,-0.150475,-0.665323,1.892024,-1.031432,0.547361,0.711206,-0.076884,0.060578,0.293545,285
2,2,3,-5.003945,0.224774,-0.568979,1.958785,5.966880,0.902570,0.560002,-0.524460,0.305597,0.092361,284
3,2,4,-5.107367,0.365191,-0.194350,1.811717,-1.145077,0.410198,0.385573,-0.290448,-0.288587,0.655261,283
4,2,5,-5.464810,0.203329,-0.452717,1.338957,6.111575,-0.381631,-0.331347,-0.626438,0.573540,0.518663,282
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16109,100,196,6.962576,-0.877323,0.938418,0.648615,0.005334,-0.627832,0.592017,0.009544,0.895433,-0.693938,4
16110,100,197,7.102584,-0.945318,1.842089,0.656173,-0.090673,0.644176,-0.373444,-0.653792,-1.055729,-0.208923,3
16111,100,198,8.083038,-0.690145,-0.041760,0.281251,0.320375,-0.329894,1.140073,-0.269687,0.766491,0.350538,2
16112,100,199,7.826214,-0.745422,-0.291177,-0.851751,0.738067,0.668139,-0.142457,-1.429173,-0.333743,0.091077,1
16113,100,200,7.925748,-1.268775,2.339487,0.179086,0.075909,-0.316345,-0.330164,-0.071645,-0.073398,-0.531459,0

In [22]:
test_datasets[0]

,Unit Number,Time (Cycles),PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10
0,1,1,-2.231481,-0.837578,-1.483258,0.039321,-0.096985,-0.219548,-0.847583,0.868045,-0.421733,-0.648312
1,1,2,-3.315484,-0.099819,1.534633,-0.376132,-0.448950,0.476275,1.281363,-0.097176,0.243924,-0.463862
2,1,3,-2.099436,-0.435696,-0.381512,-0.203652,-0.183935,-0.052920,0.364808,0.696738,-0.117188,0.982963
3,1,4,-2.606579,-0.868152,-1.345495,1.297065,-0.581376,-0.032635,-0.656365,0.031608,0.208549,-0.194751
4,1,5,-3.238460,-0.813277,-0.472825,0.366541,-0.408099,0.615776,-1.153830,0.041416,-0.129179,0.022549
...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,2.301264,5.269805,-1.612978,1.513925,-0.547512,0.576357,-0.595607,0.102750,-0.079558,-0.200974
13092,100,195,2.525270,4.784544,0.499591,-0.243667,-0.183387,-0.199227,-0.121327,0.198391,-0.847111,-0.549792
13093,100,196,2.248461,5.128793,0.830487,0.338644,-0.463487,-0.645625,-0.396984,0.553312,-0.199337,-0.567322
13094,100,197,2.413122,5.337485,0.829177,-1.560932,0.195347,-0.368381,-0.197324,0.360527,-0.555636,0.087187
13095,100,198,3.664534,5.495442,-1.237517,-0.286210,0.104569,0.438933,0.718920,0.026348,0.081763,0.396166

In [23]:
from data_helpers import fit_ElasticNet

feature = fit_ElasticNet()
train_datasets, validation_datasets, test_datasets, expected_RUL_datasets = feature.result_df()
train_datasets[0]

,Unit Number,Time (Cycles),S11,S9,S4,S12,S7,S14,S21,S15,S20,S2
0,1,1,-0.295941,-0.873456,-0.956197,0.363967,1.151888,-0.257882,1.222992,-0.631788,1.380895,-1.751275
1,1,2,-0.220789,-0.972064,-0.673151,1.207475,0.459700,-0.641287,1.265671,-0.302069,1.046885,-1.089495
2,1,3,-1.047460,-0.559491,-0.555029,1.397945,1.038415,-0.547721,0.528999,-0.677359,0.768543,-0.688417
3,1,4,-1.573524,-0.720427,-0.814674,1.996563,1.254014,-0.515457,0.804555,-2.006959,0.378865,-0.688417
4,1,5,-1.009884,-0.456697,-0.329929,1.085030,0.743384,-0.517070,1.087534,-0.366404,0.490202,-0.648309
...,...,...,...,...,...,...,...,...,...,...,...,...
16598,98,152,2.409529,0.001924,2.369037,-1.323049,-2.354441,-0.669787,-1.651326,1.992563,-2.627224,2.018861
16599,98,153,2.559832,-0.295296,1.660307,-2.125742,-1.197012,-0.345533,-2.232128,1.480560,-1.569526,2.419940
16600,98,154,2.071345,-0.279016,2.207455,-2.057717,-1.809769,-0.519221,-1.607720,1.587786,-1.346853,1.978754
16601,98,155,2.559832,-0.425068,1.757256,-2.656336,-1.707642,-0.895635,-1.853586,1.681609,-1.847868,2.540263
16602,98,156,2.785288,-0.299017,2.560706,-2.506681,-2.070757,-1.139767,-1.609576,2.351770,-2.682893,0.655195

In [24]:
for i in range(4):
    train_datasets[i] = Calculate_RUL(train_datasets[i])

In [25]:
train_datasets[0]

,Unit Number,Time (Cycles),S11,S9,S4,S12,S7,S14,S21,S15,S20,S2,RUL
0,1,1,-0.295941,-0.873456,-0.956197,0.363967,1.151888,-0.257882,1.222992,-0.631788,1.380895,-1.751275,191
1,1,2,-0.220789,-0.972064,-0.673151,1.207475,0.459700,-0.641287,1.265671,-0.302069,1.046885,-1.089495,190
2,1,3,-1.047460,-0.559491,-0.555029,1.397945,1.038415,-0.547721,0.528999,-0.677359,0.768543,-0.688417,189
3,1,4,-1.573524,-0.720427,-0.814674,1.996563,1.254014,-0.515457,0.804555,-2.006959,0.378865,-0.688417,188
4,1,5,-1.009884,-0.456697,-0.329929,1.085030,0.743384,-0.517070,1.087534,-0.366404,0.490202,-0.648309,187
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16598,98,152,2.409529,0.001924,2.369037,-1.323049,-2.354441,-0.669787,-1.651326,1.992563,-2.627224,2.018861,4
16599,98,153,2.559832,-0.295296,1.660307,-2.125742,-1.197012,-0.345533,-2.232128,1.480560,-1.569526,2.419940,3
16600,98,154,2.071345,-0.279016,2.207455,-2.057717,-1.809769,-0.519221,-1.607720,1.587786,-1.346853,1.978754,2
16601,98,155,2.559832,-0.425068,1.757256,-2.656336,-1.707642,-0.895635,-1.853586,1.681609,-1.847868,2.540263,1
16602,98,156,2.785288,-0.299017,2.560706,-2.506681,-2.070757,-1.139767,-1.609576,2.351770,-2.682893,0.655195,0

In [26]:
validation_datasets[0]

,Unit Number,Time (Cycles),S11,S9,S4,S12,S7,S14,S21,S15,S20,S2
0,21,1,-0.260058,-0.779786,0.303610,0.350607,0.120958,-0.798055,0.504842,-0.531538,0.357774,-0.776151
1,21,2,-0.967109,-0.925428,-0.373517,-0.148353,-0.270337,-1.197040,-0.639969,-1.282573,-0.130923,-0.716451
2,21,3,-0.297271,-0.742347,0.106668,-0.323663,-0.281517,-0.970007,0.429069,0.185359,-0.782519,-0.318456
3,21,4,-0.594977,-0.584362,0.169734,0.418033,-0.180898,-0.906782,1.075421,-1.235305,0.900771,-0.258756
4,21,5,0.223713,-0.777317,-0.714293,0.431519,-0.482755,-0.681186,-0.332312,1.159603,0.249175,-0.835850
...,...,...,...,...,...,...,...,...,...,...,...,...
4023,100,196,2.084374,-0.035117,2.291841,-2.710575,-2.271533,-0.361232,-2.981627,1.503609,-1.868513,1.711322
4024,100,197,1.972735,-0.051986,2.839517,-2.454353,-2.908785,-0.413919,-1.284495,1.984166,-2.900207,1.810821
4025,100,198,2.158801,-0.019484,2.242052,-2.009335,-2.819346,-0.195987,-3.348624,3.315546,-2.140011,1.572024
4026,100,199,3.275197,0.302246,2.059493,-2.467838,-3.110023,-0.280286,-2.155428,2.640665,-2.954506,1.193928
4027,100,200,2.568146,-0.201331,2.680193,-2.966797,-2.987044,-0.374165,-2.263153,1.713689,-2.520109,2.427714