In [1]:
from preprocessing_pca import fit_pca
from data_helpers import DataHolder

data = DataHolder()
train_datasets, test_datasets, expected_RUL_datasets = data.get()

feature = fit_pca(train_datasets, test_datasets, expected_RUL_datasets)
train_datasets, test_datasets, expected_RUL_datasets = feature.result_df()

In [2]:
def Calculate_RUL(df):
    max_cycles = df.groupby('Unit Number')['Time (Cycles)'].max()
    merged = df.merge(max_cycles.to_frame(name='max_time_cycle'), left_on='Unit Number',right_index=True)
    merged["RUL"] = merged["max_time_cycle"] - merged['Time (Cycles)']
    merged = merged.drop("max_time_cycle", axis=1)
    return merged

In [3]:
for i in range(4):
    train_datasets[i] = Calculate_RUL(train_datasets[i])

In [4]:
train_datasets[3]

,Unit Number,Time (Cycles),PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10,RUL
0,1,1,-3.015023,-2.202168,-0.212861,0.004079,0.012118,-0.119927,-0.097312,-0.121166,0.026984,-0.033107,320
1,1,2,1.469597,-0.389370,1.624185,0.086131,-0.111275,-0.146623,0.112017,-0.082148,0.021783,0.039646,319
2,1,3,-3.061170,-2.154521,-0.179298,0.045399,-0.010963,-0.190349,-0.122244,-0.070166,0.062872,-0.025807,318
3,1,4,-3.012203,-2.201073,-0.261818,-0.026984,0.007403,-0.139130,-0.065482,-0.108467,0.041192,-0.033449,317
4,1,5,-6.066693,4.297044,0.000600,0.022087,-0.126427,-0.035908,-0.036928,-0.083133,-0.010179,0.011829,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61244,249,251,4.213778,-0.009761,-1.124569,-0.047547,0.242163,0.302858,0.273255,0.038321,-0.120634,0.044439,4
61245,249,252,7.605931,1.275142,-0.116293,-0.411623,0.325816,0.314174,-0.091975,0.004945,-0.156461,-0.032445,3
61246,249,253,7.671169,1.257007,-0.122943,-0.426780,0.404812,0.373021,-0.096834,0.062236,-0.137361,0.038214,2
61247,249,254,-1.680432,-1.951926,-0.147149,-0.360592,-0.006212,0.433859,0.132905,0.077529,-0.199031,0.022189,1
61248,249,255,-2.462516,-2.532017,-0.532672,-0.289309,0.540454,0.248367,0.142101,-0.034934,-0.140613,0.034519,0

In [5]:
test_datasets[3]

,Unit Number,Time (Cycles),PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10
0,1,1,1.455502,-0.385731,1.631894,0.091886,-0.114074,-0.113163,0.122561,-0.087728,0.069559,0.079452
1,1,2,-6.090458,4.329211,0.022114,0.038731,-0.158762,-0.035487,-0.017696,-0.113204,0.044688,0.025707
2,1,3,-3.098689,-2.166248,-0.201426,0.024057,-0.043218,-0.129818,-0.099219,-0.123764,0.111120,-0.012944
3,1,4,-3.064131,-2.212687,-0.241819,-0.011640,0.005516,-0.085170,-0.096632,-0.116447,0.077191,-0.027416
4,1,5,-2.262396,-1.610898,0.134049,-0.076948,-0.526831,0.050958,-0.047500,-0.015184,0.046406,-0.042639
...,...,...,...,...,...,...,...,...,...,...,...,...
41209,248,277,-2.793628,-2.332873,-0.293994,-0.052661,0.390429,0.087620,-0.033899,0.078748,0.119974,0.074246
41210,248,278,1.743833,-0.531391,1.582587,0.041731,0.312193,0.104255,0.144512,0.117026,0.080965,0.048150
41211,248,279,-2.012619,-1.784914,0.069472,-0.129896,-0.091179,0.313804,-0.031835,0.218027,0.095445,-0.000412
41212,248,280,2.158453,-0.302161,0.286824,1.579007,0.096925,0.344964,-0.256396,-0.043370,0.067240,-0.001671
41213,248,281,-1.989280,-1.766836,0.090733,-0.113762,-0.077532,0.292359,-0.014491,0.197715,0.103759,0.067353

In [6]:
from data_helpers import DataHolder
from preprocessing_ElasticNet import fit_ElasticNet

data = DataHolder()
train_datasets, test_datasets, expected_RUL_datasets = data.get()

feature = fit_ElasticNet(train_datasets, test_datasets, expected_RUL_datasets)
train_datasets, test_datasets, expected_RUL_datasets = feature.result_df()

In [7]:
for i in range(4):
    train_datasets[i] = Calculate_RUL(train_datasets[i])

In [8]:
train_datasets[3]

,Unit Number,Time (Cycles),S14,S11,S4,S16,S15,S18,S8,OP2,OP3,S19,RUL
0,1,1,0.081921,-0.365205,-0.745729,-0.694278,0.063831,-0.114203,-0.115765,0.864668,0.418783,0.418783,320
1,1,2,-0.253086,0.328498,0.298212,-0.694278,-0.125677,0.655708,0.653429,0.414718,0.418783,0.418783,319
2,1,3,-0.013912,-0.374454,-0.711202,-0.694278,0.153387,-0.114203,-0.115352,0.867565,0.418783,0.418783,318
3,1,4,0.096162,-0.368288,-0.702990,-0.694278,0.068362,-0.114203,-0.115627,0.864668,0.418783,0.418783,317
4,1,5,-2.358027,-1.971512,-1.410627,-0.694278,2.066982,-2.155843,-2.156673,0.158844,-2.387873,-2.387873,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61244,249,251,1.375959,0.988286,0.950036,1.440345,-1.108128,0.621337,0.625909,-1.034264,0.418783,0.418783,4
61245,249,252,1.373391,1.592578,1.884363,1.440345,-1.417310,1.095657,1.099327,-1.834069,0.418783,0.418783,3
61246,249,253,1.472259,1.654240,1.916124,1.440345,-1.376797,1.095657,1.099602,-1.838897,0.418783,0.418783,2
61247,249,254,0.675012,-0.106223,-0.450322,-0.694278,-0.311985,-0.038587,-0.033754,0.864668,0.418783,0.418783,1
61248,249,255,0.893175,-0.084641,-0.456439,-0.694278,-0.219764,-0.114203,-0.111224,0.864668,0.418783,0.418783,0

In [9]:
test_datasets[3]

,Unit Number,Time (Cycles),S14,S11,S4,S16,S15,S18,S8,OP2,OP3,S19
0,1,1,-0.219818,0.294583,0.217006,-0.694278,-0.083564,0.655708,0.653498,0.414074,0.418783,0.418783
1,1,2,-2.385341,-2.085587,-1.428310,-0.694278,2.102432,-2.155843,-2.156742,0.156591,-2.387873,-2.387873
2,1,3,0.038732,-0.417618,-0.804811,-0.694278,0.147123,-0.114203,-0.115283,0.871105,0.418783,0.418783
3,1,4,0.129313,-0.352872,-0.793246,-0.694278,0.098347,-0.114203,-0.115558,0.865312,0.418783,0.418783
4,1,5,-0.116515,-0.479280,-0.704917,-0.694278,0.023184,-0.038587,-0.041116,0.864668,0.418783,0.418783
...,...,...,...,...,...,...,...,...,...,...,...,...
41209,248,277,0.522917,-0.177134,-0.609632,-0.694278,0.209359,-0.114203,-0.112393,0.864990,0.418783,0.418783
41210,248,278,0.221994,0.510402,0.494145,-0.694278,-0.011199,0.655708,0.657351,0.415683,0.418783,0.418783
41211,248,279,0.385529,-0.167885,-0.594548,-0.694278,0.150055,-0.038587,-0.035199,0.868852,0.418783,0.418783
41212,248,280,0.203434,0.587480,0.455344,1.440345,-0.017196,0.655708,0.657075,0.414074,0.418783,0.418783
41213,248,281,0.354363,-0.244963,-0.513007,-0.694278,0.147656,-0.038587,-0.035680,0.865312,0.418783,0.418783